// ─────────────────────────────────────────────────────────────────────────────
// scriptGeneratorService.js
// Generates Windows Batch (.bat) scripts for silent tool installation.
//
// Key design decisions:
// 1. Uses curl.exe (built into Windows 10/11) instead of Invoke-WebRequest
//    because curl handles redirects, query-param URLs, and large files
//    much more reliably. Invoke-WebRequest fails on Oracle CDN, redirect
//    chains, and URLs with query params.
// 2. Filenames are derived safely — never from URL path which may have
//    query params or redirect paths.
// 3. Admin check at script start.
// 4. PATH additions use reg add to the registry, not setx %PATH% which
//    truncates on long paths.
// ─────────────────────────────────────────────────────────────────────────────

const HEADER = `@echo off
setlocal EnableDelayedExpansion
title Automated Developer Environment Setup
color 0A
echo.
echo  =====================================================
echo   AUTOMATED DEVELOPER ENVIRONMENT SETUP
echo   Generated by DevSetup Generator
echo  =====================================================
echo.

REM ── Admin check ──────────────────────────────────────
net session >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo  [WARN] Not running as Administrator!
    echo  [WARN] Right-click this .bat file and choose
    echo  [WARN] "Run as Administrator" then try again.
    echo.
    pause
    exit /b 1
)
echo  [OK] Running as Administrator.
echo.

REM ── curl.exe check (built-in on Windows 10/11) ───────
where curl >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo  [ERROR] curl.exe not found. Please update Windows
    echo          to version 1803 or later and try again.
    pause
    exit /b 1
)
echo  [OK] curl.exe found.
echo.
echo  Press any key to begin installation...
pause >nul
echo.
`

const FOOTER = (tools) => {
  const list = tools.map((t, i) => `echo   [${i + 1}] ${t.toolName} ${t.version}`).join('\n')
  return `
echo.
echo  =====================================================
echo   ALL INSTALLATIONS COMPLETE!
echo  =====================================================
echo.
echo  Installed tools:
${list}
echo.
echo  IMPORTANT: Restart your PC or open a new terminal
echo  window for all PATH changes to take effect.
echo.
pause
exit /b 0
`
}

// Generate a safe, unique local filename for each tool's installer
// Based on slug + version + extension — completely ignores the URL path
const getInstallerFilename = (tool, version) => {
  const safeName = (tool.slug + '_' + version.version)
    .replace(/[^a-zA-Z0-9._-]/g, '_')
    .replace(/_+/g, '_')
    .substring(0, 60)

  // Determine extension based on URL
  const url = version.installerUrl.toLowerCase()
  if (url.includes('.msi')) return `${safeName}.msi`
  if (url.includes('.zip')) return `${safeName}.zip`
  if (url.includes('msi')) return `${safeName}.msi`
  // Default to .exe for everything else (installers, redirect URLs)
  return `${safeName}.exe`
}

// Download block using curl.exe
// curl handles: redirects, query-param URLs, Oracle CDN, all vendor CDNs
const DOWNLOAD_BLOCK = (tool, version) => {
  const filename = getInstallerFilename(tool, version)
  return {
    filename,
    block: `echo [INFO] Downloading ${tool.name} ${version.version}...
curl.exe -L --retry 3 --retry-delay 3 --progress-bar -o "%TEMP%\\${filename}" "${version.installerUrl}"
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to download ${tool.name}.
    echo         Check your internet connection and try again.
    pause
    exit /b 1
)
echo [OK] Download complete.`
  }
}

// PATH addition via registry — safe, does not truncate existing PATH
const ADD_TO_PATH = (pathToAdd, toolName) => {
  if (!pathToAdd) return ''
  return `
REM Add ${toolName} to system PATH
for /f "skip=2 tokens=2,*" %%a in ('reg query "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment" /v PATH 2^>nul') do set "CURRENT_PATH=%%b"
echo !CURRENT_PATH! | findstr /i /c:"${pathToAdd}" >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment" /v PATH /t REG_EXPAND_SZ /d "!CURRENT_PATH!;${pathToAdd}" /f >nul
    echo [OK] Added "${pathToAdd}" to system PATH.
) else (
    echo [INFO] "${pathToAdd}" already in PATH.
)
`
}

// Set an environment variable in the system registry
const SET_ENV_VAR = (varName, value) => {
  if (!varName || !value) return ''
  return `setx ${varName} "${value}" /M
if %ERRORLEVEL% NEQ 0 (
    echo [WARN] Could not set ${varName}. Continuing anyway.
) else (
    echo [OK] ${varName} = "${value}"
)
`
}

// Verify a tool is in PATH after install
const VERIFY_BLOCK = (toolName, verifyCmd) => {
  if (!verifyCmd) return ''
  const label = toolName.toUpperCase().replace(/[^A-Z0-9]/g, '_')
  return `
set _RETRY_${label}=0
:retry_${label}
${verifyCmd} >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    set /a _RETRY_${label}+=1
    if !_RETRY_${label}! GEQ 5 (
        echo [WARN] ${toolName} not found in PATH after 5 retries.
        echo        Try opening a new terminal after the script finishes.
        goto end_verify_${label}
    )
    echo [WAIT] ${toolName} not in PATH yet - retry !_RETRY_${label}!/5...
    timeout /t 3 /nobreak >nul
    goto retry_${label}
)
echo [OK] ${toolName} verified in PATH.
:end_verify_${label}
`
}

// ── Tool block generators ──────────────────────────────────────────────────

const generateEnvOnlyBlock = (tool, version, stepNum, total) => {
  const zipFilename = getInstallerFilename(tool, version)
  const installDir = tool.installDir || `C:\\${tool.slug}`
  const { block: downloadBlock } = DOWNLOAD_BLOCK(tool, version)

  return `
REM ─────────────────────────────────────────────────────
REM  STEP ${stepNum}/${total}: ${tool.name} ${version.version}
REM ─────────────────────────────────────────────────────
echo [${stepNum}/${total}] Setting up ${tool.name} ${version.version}...
${downloadBlock}

echo [INFO] Extracting ${tool.name} to ${installDir}...
if not exist "${installDir}" mkdir "${installDir}"
powershell -NoProfile -Command "Expand-Archive -Path '%TEMP%\\${zipFilename}' -DestinationPath '%TEMP%\\${tool.slug}_tmp' -Force"
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to extract ${tool.name} archive.
    pause
    exit /b 1
)
REM Move extracted folder contents into install directory
for /d %%D in ("%TEMP%\\${tool.slug}_tmp\\*") do (
    robocopy "%%D" "${installDir}" /E /NFL /NDL /NJH /NJS /nc /ns /np >nul
)
${tool.envVar ? SET_ENV_VAR(tool.envVar, installDir) : ''}
${tool.envPath ? ADD_TO_PATH(tool.envPath, tool.name) : ''}
${VERIFY_BLOCK(tool.name, tool.verifyCommand)}
echo [DONE] ${tool.name} ${version.version} ready.
echo.
`
}

const generateInstallBlock = (tool, version, stepNum, total) => {
  const { filename, block: downloadBlock } = DOWNLOAD_BLOCK(tool, version)
  const ext = filename.split('.').pop().toLowerCase()
  
  // MSI installer command
  const installCmd = ext === 'msi'
    ? `msiexec /i "%TEMP%\\${filename}" ${version.silentFlags} /L*V "%TEMP%\\${tool.slug}_install.log"`
    : `start /wait "" "%TEMP%\\${filename}" ${version.silentFlags}`

  return `
REM ─────────────────────────────────────────────────────
REM  STEP ${stepNum}/${total}: ${tool.name} ${version.version}
REM ─────────────────────────────────────────────────────
echo [${stepNum}/${total}] Installing ${tool.name} ${version.version}...
${downloadBlock}

echo [INFO] Running ${tool.name} installer silently...
${installCmd}
set _EXIT=${ext === 'msi' ? '%ERRORLEVEL%' : '%ERRORLEVEL%'}
if !_EXIT! NEQ 0 (
    echo [WARN] Installer returned code !_EXIT! for ${tool.name}.
    echo        This may be normal for some installers - continuing.
)
echo [OK] ${tool.name} installer finished.
${tool.envVar && tool.installDir ? SET_ENV_VAR(tool.envVar, tool.installDir) : ''}
${tool.envPath && tool.installDir ? ADD_TO_PATH(tool.envPath, tool.name) : ''}
${VERIFY_BLOCK(tool.name, tool.verifyCommand)}
echo [DONE] ${tool.name} ${version.version} complete.
echo.
`
}

// ── Dependency resolver ────────────────────────────────────────────────────

const resolveDependencyOrder = (selectedTools) => {
  const slugMap = new Map(selectedTools.map(t => [t.slug, t]))
  const visited = new Set()
  const result = []

  const visit = (slug) => {
    if (visited.has(slug)) return
    visited.add(slug)
    const tool = slugMap.get(slug)
    if (!tool) return
    for (const prereq of (tool.prerequisites || [])) {
      if (slugMap.has(prereq)) visit(prereq)
    }
    result.push(tool)
  }

  for (const tool of selectedTools) visit(tool.slug)
  return result
}

// ── Main export ────────────────────────────────────────────────────────────

export const generateBatchScript = (toolsWithVersions) => {
  const ordered = resolveDependencyOrder(toolsWithVersions)
  const total = ordered.length

  let script = HEADER
  script += `echo  Installing ${total} tool(s)...\n`
  script += `echo.\n\n`

  ordered.forEach((tool, idx) => {
    const version = tool.selectedVersion
    if (tool.isEnvOnly) {
      script += generateEnvOnlyBlock(tool, version, idx + 1, total)
    } else {
      script += generateInstallBlock(tool, version, idx + 1, total)
    }
  })

  script += FOOTER(ordered.map(t => ({
    toolName: t.name,
    version: t.selectedVersion.version
  })))

  return script
}
