// ─────────────────────────────────────────────────────────────────────────────
// scriptGeneratorService.js
// Generates a Windows Batch (.bat) script for silent tool installation.
// ─────────────────────────────────────────────────────────────────────────────

const HEADER = `@echo off
setlocal EnableDelayedExpansion
title Automated Developer Environment Setup
color 0A
echo.
echo  =====================================================
echo   AUTOMATED DEVELOPER ENVIRONMENT SETUP
echo   Generated by DevSetup Generator
echo  =====================================================
echo.
echo  IMPORTANT: Right-click this file and select
echo  "Run as Administrator" for best results.
echo.
echo  Press any key to begin...
pause >nul
echo.

REM Check for admin rights
net session >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo [WARN] Not running as Administrator. Some installs may fail.
    echo        Right-click the script and choose "Run as Administrator".
    echo.
    timeout /t 5 /nobreak >nul
)
`

const FOOTER = (tools) => {
  const list = tools.map((t, i) => `echo   [${i + 1}] ${t.toolName} ${t.version}`).join('\n')
  return `
REM =====================================================
REM  INSTALLATION COMPLETE
REM =====================================================
echo.
echo  =====================================================
echo   ALL DONE!
echo  =====================================================
echo.
echo  Installed tools:
${list}
echo.
echo  ACTION REQUIRED:
echo  Please RESTART your PC or open a new terminal
echo  for all PATH and environment variable changes
echo  to take effect.
echo.
pause
exit /b 0
`
}

// Safe filename: strip query params and sanitize
const safeFilename = (url, fallbackName) => {
  try {
    const pathname = new URL(url).pathname
    const base = pathname.split('/').pop()
    // If no extension found (e.g. redirect URLs), use the fallback
    if (!base || !base.includes('.')) return fallbackName
    return base.replace(/[^a-zA-Z0-9._-]/g, '_')
  } catch {
    return fallbackName
  }
}

const VERIFY_BLOCK = (toolName, verifyCmd) => {
  if (!verifyCmd) return ''
  const label = toolName.toUpperCase().replace(/[^A-Z0-9]/g, '_')
  return `
set RETRY_${label}=0
:retry_${label}
${verifyCmd} >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    set /a RETRY_${label}+=1
    if !RETRY_${label}! GEQ 5 (
        echo [WARN] ${toolName} not found in PATH after 5 retries.
        echo        You may need to restart your terminal.
        goto skip_verify_${label}
    )
    echo [WAIT] ${toolName} not in PATH yet. Retry !RETRY_${label}!/5 in 3s...
    timeout /t 3 /nobreak >nul
    goto retry_${label}
)
echo [OK] ${toolName} verified in PATH.
:skip_verify_${label}
`
}

// FIX: Do NOT use setx PATH "%PATH%;..." — that reads the current process PATH
// which may already be expanded/duplicated. Use reg add to append to the
// system PATH in the registry directly.
const ENV_BLOCK = (envVar, installDir, envPath) => {
  if (!envVar && !envPath) return ''
  let block = '\nREM ── Setting environment variables ──\n'
  if (envVar && installDir) {
    block += `setx ${envVar} "${installDir}" /M\n`
    block += `if %ERRORLEVEL% NEQ 0 echo [WARN] Could not set ${envVar} - run as Admin\n`
    block += `echo [OK] ${envVar} = "${installDir}"\n`
  }
  if (envPath) {
    // Append to system PATH via registry — safe and does not truncate
    block += `for /f "tokens=2,*" %%a in ('reg query "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment" /v PATH 2^>nul ^| findstr /i "PATH"') do set SYSPATH=%%b\n`
    block += `echo !SYSPATH! | findstr /i /c:"${envPath}" >nul 2>&1\n`
    block += `if %ERRORLEVEL% NEQ 0 (\n`
    block += `    reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment" /v PATH /t REG_EXPAND_SZ /d "!SYSPATH!;${envPath}" /f >nul\n`
    block += `    echo [OK] Added ${envPath} to system PATH\n`
    block += `) else (\n`
    block += `    echo [INFO] ${envPath} already in PATH, skipping.\n`
    block += `)\n`
  }
  return block
}

const generateToolBlock = (tool, selectedVersion, stepNum, totalSteps) => {
  const divider = `REM ${'─'.repeat(54)}`
  const stepHeader = `echo [${stepNum}/${totalSteps}] Installing ${tool.name} ${selectedVersion.version}...`

  // env-only tools (Maven, Gradle) — zip extract + set PATH
  if (tool.isEnvOnly) {
    const zipName = safeFilename(selectedVersion.installerUrl, `${tool.slug}.zip`)
    const extractDir = tool.installDir || `C:\\${tool.slug}`
    return `
${divider}
REM  STEP ${stepNum}/${totalSteps}: ${tool.name.toUpperCase()} ${selectedVersion.version}
${divider}
${stepHeader}
echo [INFO] Downloading ${tool.name} archive...
powershell -Command "Invoke-WebRequest -Uri '${selectedVersion.installerUrl}' -OutFile '%TEMP%\\${zipName}' -UseBasicParsing"
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to download ${tool.name}. Check your internet connection.
    pause
    exit /b 1
)
echo [INFO] Extracting ${tool.name} to ${extractDir}...
if not exist "${extractDir}" mkdir "${extractDir}"
powershell -Command "Expand-Archive -Path '%TEMP%\\${zipName}' -DestinationPath '%TEMP%\\${tool.slug}_extract' -Force"
REM Move top-level folder contents into install dir
for /d %%i in ("%TEMP%\\${tool.slug}_extract\\*") do (
    robocopy "%%i" "${extractDir}" /E /NFL /NDL /NJH /NJS >nul
)
${ENV_BLOCK(tool.envVar, extractDir, tool.envPath?.replace(tool.installDir || '', extractDir))}
${VERIFY_BLOCK(tool.name, tool.verifyCommand)}
echo [DONE] ${tool.name} ${selectedVersion.version} configured.
echo.
`
  }

  const filename = safeFilename(selectedVersion.installerUrl, `${tool.slug}_installer.exe`)

  return `
${divider}
REM  STEP ${stepNum}/${totalSteps}: ${tool.name.toUpperCase()} ${selectedVersion.version}
${divider}
${stepHeader}
echo [INFO] Downloading installer from official source...
powershell -Command "Invoke-WebRequest -Uri '${selectedVersion.installerUrl}' -OutFile '%TEMP%\\${filename}' -UseBasicParsing"
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to download ${tool.name}. Check your internet connection.
    pause
    exit /b 1
)
echo [INFO] Running silent install for ${tool.name}...
start /wait "" "%TEMP%\\${filename}" ${selectedVersion.silentFlags}
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] ${tool.name} installer exited with code %ERRORLEVEL%.
    echo         This may be a false positive for some installers. Continuing...
)
echo [OK] ${tool.name} installer finished.
${VERIFY_BLOCK(tool.name, tool.verifyCommand)}
${ENV_BLOCK(tool.envVar, tool.installDir, tool.envPath)}
echo [DONE] ${tool.name} ${selectedVersion.version} complete.
echo.
`
}

const resolveDependencyOrder = (selectedTools) => {
  const slugToTool = new Map(selectedTools.map(t => [t.slug, t]))
  const visited = new Set()
  const result = []

  const visit = (slug) => {
    if (visited.has(slug)) return
    visited.add(slug)
    const tool = slugToTool.get(slug)
    if (!tool) return
    for (const prereq of (tool.prerequisites || [])) {
      if (slugToTool.has(prereq)) visit(prereq)
    }
    result.push(tool)
  }

  for (const tool of selectedTools) visit(tool.slug)
  return result
}

export const generateBatchScript = (toolsWithVersions) => {
  const ordered = resolveDependencyOrder(toolsWithVersions)
  const total = ordered.length

  let script = HEADER
  script += `echo  Installing ${total} tool(s)...\n`
  script += `echo.\n\n`

  ordered.forEach((tool, idx) => {
    script += generateToolBlock(tool, tool.selectedVersion, idx + 1, total)
  })

  script += FOOTER(ordered.map(t => ({ toolName: t.name, version: t.selectedVersion.version })))
  return script
}